# Generated by Django 4.1 on 2022-08-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
    ]
